server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848    #nacos地址
      discovery:
        namespace: 3f8f6d1a-7b47-4bfb-8c3b-3a35e971de5c
    gateway:
      routes:
        - id: user-service   #路由标识 必须唯一
          uri: lb://userservice   #路由的目标地址
          predicates:   #路由断言，判断是否符合规则
            - Path=/user/**   #路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service   #路由标识 必须唯一
          uri: lb://orderservice   #路由的目标地址
          predicates: #路由断言，判断是否符合规则
            - Path=/order/**   #路径断言，判断路径是否是以/order，如果是则符合
      default-filters:
        - AddRequestHeader=desc, LSSB