server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/cloud-user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/

logging:
  level:
    com.luos: debug
  pattern:
    dateformat: MM-dd HH:ss:SSS