server:
  port: 8081
spring:
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/cloud-order?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/
  cloud:
    nacos:
      server-addr: localhost:8848